### PR TITLE
Some bug fixes and enhancements.

### PR DESCRIPTION
**Pull request by daschatten**
Hi,

this formula did not work out of the box because of some bugs like wrong tags: {% %} instead of {{ }}. Also under debian wheezy the wrong package (squid 2.x) was installed. I added a map.jinja file for multiple distro support and for debian wheezy it install squid3. This fixes the missing ipv6 support error which occured with squid 2.x and configuration directives like 'acl localnet src fc00::/7'
Also a pillar.example was added.

These commits break the squid formula for users with other distros than debian. In this case the missing configuration has to be added to squid/map.jinja.

### CODE REVIEW

**Comment by gravyboat** [comment]
Good stuff, thanks @daschatten!

**Comment by gravyboat** [comment]
I should mention, don't forget with the jinja stuff if you have a TON of content that needs to go from the pillar to the file, you can do something like this (adding a 'settings' section as an example):

```
squid:
  settings:
    cache_mgr_user: username
    cache_mgr_password: password
```

```
{% for item in pillar['squid']['settings'] -%}
{{ item }}: {{ pillar['squid']['settings'][item] }}
{% endfor -%}
```

**Comment by daschatten** [comment]
@gravyboat: I'm aware of this method but in this case i decided against. Right now i'm on my way finding which method is best in what situation. There are many possibilities :-)

**Comment by gravyboat** [comment]
@daschatten Works for me! I just wasn't sure if it would be easier in the event there were a lot more Squid configuration items that we might need to support. Glad you've already looked into it.

**Pull request merged**
